config/routes.rb
SuperZapatos::Application.routes.draw do
  
  root to: 'stores#index'
  
  resources :articles

  resources :stores

  mount Services::API => "/"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_reader :store_name
  attr_accessible :description, :name, :price, :total_in_shelf, :total_in_vault, :store_id
  belongs_to :stores
  
  def store_name
    @store_name = Store.find(self.store_id).name
  end

end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :address, :name, :store_id
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new
   
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    
    @article = Article.new(params[:article])
    
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

	<ul>
		<% @article.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :name %>
	<br />
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :description %>
	<br />
	<%= f.text_field :description %>
</div>
<div class="field">
	<%= f.label :price %>
	<br />
	<%= f.text_field :price %>
</div>
<div class="field">
	<%= f.label :total_in_shelf %>
	<br />
	<%= f.number_field :total_in_shelf %>
</div>
<div class="field">
	<%= f.label :total_in_vault %>
	<br />
	<%= f.number_field :total_in_vault %>
</div>

<div class="field">
	<%= f.label :store_name %>
	<br />
	<%= select("article", "store_id", Store.all.collect {|s| [ s.name, s.id]})%>
</div>

<div class="actions">
	<%= f.submit :class => "btn btn-primary"%>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article,:class => "btn btn-link" %> |
<%= link_to 'Back', articles_path,:class => "btn btn-link" %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table class="table table-striped">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Price</th>
		<th>Total in shelf</th>
		<th>Total in vault</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @articles.each do |article| %>
	<tr>
		<td><%= article.name %></td>
		<td><%= article.description %></td>
		<td><%= article.price %></td>
		<td><%= article.total_in_shelf %></td>
		<td><%= article.total_in_vault %></td>
		<td><%= link_to 'Show', article %></td>
		<td><%= link_to 'Edit', edit_article_path(article) %></td>
		<td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<% end %>
</table>

<%= link_to 'New Article', new_article_path,:class => "btn btn-primary" %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path,:class => "btn btn-link" %>

app/views/articles/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<b>Name:</b>
	<%= @article.name %>
</p>

<p>
	<b>Description:</b>
	<%= @article.description %>
</p>

<p>
	<b>Price:</b>
	<%= @article.price %>
</p>

<p>
	<b>Total in shelf:</b>
	<%= @article.total_in_shelf %>
</p>

<p>
	<b>Total in vault:</b>
	<%= @article.total_in_vault %>
</p>

<%= link_to 'Edit', edit_article_path(@article),:class => "btn btn-link" %> |
<%= link_to 'Back', articles_path ,:class => "btn btn-link"%>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">	
		<p class="pull-right">
			© Copyright 2013, Super Zapatos.
		</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Super Zapatos", root_path, id: "logo", class: "brand" %>
			<nav>
				<ul class="nav pull-right">
					<li>
						<%= link_to "Stores", root_path %>
					</li>
					<li>
						<%= link_to "Articles", articles_path %>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SuperZapatos</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim'%>
	</head>
	<body>
		<%= render 'layouts/header'%>
		<div class="container">
			<%= yield %>
		</div>
		<%= render 'layouts/footer'%>
	</body>
</html>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store,:class => "btn btn-link" %> |
<%= link_to 'Back', stores_path,:class => "btn btn-link" %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table class="table table-striped">
	<tr>
		<th>Name</th>
		<th>Address</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @stores.each do |store| %>
	<tr>
		<td><%= store.name %></td>
		<td><%= store.address %></td>
		<td><%= link_to 'Show', store,:class => "btn btn-link" %></td>
		<td><%= link_to 'Edit', edit_store_path(store),:class => "btn btn-link" %></td>
		<td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?'} ,:class => "btn btn-link" %></td>
	</tr>
	<% end %>
</table>

<%= link_to 'New Store', new_store_path,:class => "btn btn-primary" %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path,:class => "btn btn-link" %>

app/views/stores/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<b>Name:</b>
	<%= @store.name %>
</p>

<p>
	<b>Address:</b>
	<%= @store.address %>
</p>

<%= link_to 'Edit', edit_store_path(@store),:class => "btn btn-link" %> |
<%= link_to 'Back', stores_path,:class => "btn btn-link" %>